version: "3.8"

services:
  duplicati:
    image: duplicati/duplicati:2.2.0.103
    container_name: duplicati
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=994 # Your user ID
      - PGID=100 # Your group ID
      - TZ=Asia/Kolkata
      - CLI_ARGS=
      - DUPLICATI_WEBROOT=/duplicati
      - DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES=homecloud
      - DUPLICATI_ALLOW_REMOTE=true
      - DOTNET_SYSTEM_IO_DISABLEFILELOCKING=true
      - DUPLICATI_PRELOAD_SETTINGS=/run/secrets/preloadsettings
    secrets:
      - preloadsettings
    volumes:
      - /var/lib/duplicati/config:/data
      - /var/lib/duplicati/backups:/backups
      - /var/lib/duplicati/shared:/shared
      - /home:/appsbackup/drive
      - /var/lib/immich:/appsbackup/immich
      - /var/lib/paperless:/appsbackup/paperless
      - /var/lib/vwdata:/appsbackup/vaultwarden
      - /var/lib/joplin:/appsbackup/joplin
      - /var/lib/jellyfin:/appsbackup/jellyfin
      - /var/lib/urbackup:/appsbackup/urbackup
      - /etc:/appsbackup/config
    ports:
      - 8200
    labels:
      - traefik.enable=true

      # Router
      - traefik.http.routers.duplicati.entrypoints=duplicati
      - traefik.http.routers.duplicati.tls=true
      - traefik.http.routers.duplicati.rule=PathPrefix(`/`)

      # Service
      - traefik.http.services.duplicati.loadbalancer.server.port=8200
      # Middleware: redirect /duplicati â†’ /duplicati/ngax/
      - traefik.http.middlewares.duplicati-redirect.replacepathregex.regex=^/duplicati/?$
      - traefik.http.middlewares.duplicati-redirect.replacepathregex.replacement=/duplicati/ngax/
      - traefik.http.routers.duplicati.middlewares=duplicati-redirect
  service-helper:
    container_name: service-helper
    entrypoint:
    - /bin/sh
    - -c
    - /shared/service_watcher.sh
    image: curlimages/curl:latest
    restart: unless-stopped
    volumes:
    - /var/lib/duplicati/shared:/shared

secrets:
  preloadsettings:
    file: /etc/duplicati/preload.json