version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.urbackup.access"
  position: 80
  text: _("Access")
  icon: connection
  url: "/startconfiguration/apps/urbackup/access"