version: "1.0"
type: navigation-item
data:
  path: "startconfiguration.apps.urbackup.password"
  position: 70
  text: _("Password")
  icon: "mdi:lock"
  url: "/startconfiguration/apps/urbackup/password"